### ISSUE TITLE
Parsing AdditionalDescriptions for the Date and Time

### ISSUE THREAD

**Issue by mapptech** [CityOfNewYork/CROL-Parsing#22]
Current next step(s):

Objective: Check if readable date and time in the AdditionalDescriptions field. 
Sub-tasks: 1.Use dateutil.parser to find all valid dates and time in the AdditionalDescriptions field. 
2. Create Summary spreadsheet that # of dates and time found for each record id.
3. Create Detail spreadsheet that list each date and time for each record id.
Delivery: Estimated Monday the 23rd

**Comment by mapptech** [comment]
Update for extracting date and time from the AdditionalDescriptions field.

Code: https://github.com/CityOfNewYork/CROL-PDF/blob/master/Planned%20Implementation/code/DateFind.py

Estimated Run Time: 90 minutes

Problems:
1.Unable to retrieve all dates and time from the field.  Get at most the first three dates.

2. Numbers extracted as dates.

**Comment by kiddle** [comment]
This task is closed, and moved over to #37
