### ISSUE TITLE
Create Consistent Parsing Error Messages

### ISSUE THREAD

**Issue by kiddle** [CityOfNewYork/CROL-Parsing#32]
For each record that fails to be parsed create an output that has:
1. RequestID
2. StartDate
3. EndDate
4. DueDate

@Mikael Should any other fields be included?

**Comment by mikaelmh1** [comment]
This sounds good. This adds additional information that allows us to further pinpoint the issue. Will the attempted parsed field (eg. "AdditionalDescription") also be included in the output??

**Comment by kiddle** [comment]
This will be addressed by our current workflow of developing json schema and data parser to document "what we have".
