### ISSUE TITLE
Microsoft SQL: Create and deploy and read/write DB

### ISSUE THREAD

**Issue by mikaelmh** [CityOfNewYork/CROL-Parsing#35]
The mSQL db will serve as an access point for CROW parsers to get data. DCAS will upload their DB dump to the DB.

**Comment by jqnatividad** [comment]
Spun up SQL Server Enterprise Edition v11.00.2100.60.v1
Here's the access point:

crol.c52iludhq0fe.us-east-1.rds.amazonaws.com:1433

However, for security purposes, can you provide a list of IPs from which access can be allowed?  Leaving port 1433 open to the world is not a viable option.  I'll send you the login details via email.
