### ISSUE TITLE
Set up MSQL server 2008R2 or 2012

### ISSUE THREAD

**Issue by noneck** [CityOfNewYork/CROL-Parsing#38]

**Comment by jqnatividad** [comment]
I guess SQL Server Enterprise Edition v11.00.2100.60.v1 (#35) is no good.

While you're there, can you get the IP address that I can include in the AWS firewall for DoITT access?  Can you also get their GH userids?

**Comment by noneck** [comment]
@jqnatividad Sure. We are meeting with them right now. Do you have any other questions?

**Comment by jqnatividad** [comment]
If @joelbcastillo is there, to see if he has any feedback about https://github.com/CityOfNewYork/DORIS-Publications-Portal/pull/18

Also Closing #35.

**Comment by jqnatividad** [comment]
Up and running and access info sent to project stakeholders.

**Comment by bmadhusu** [comment]
can you send to me? I want to check it out as well. thx!
